name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Zip
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r gc-function-source.zip backend

      - name: Upload zip
        uses: actions/upload-artifact@v3
        with:
          name: gc-function-source.zip
          path: gc-function-source.zip

      - name: Sync
        uses: patrickwyler/gcs-bucket-sync-action@1.3
        with:
          secrets: ${{ secrets.google_service_account_credentials }}
          bucket: 'bedpresbot'
          exclude: '.*\.md$|\.gitignore$|\.git/.*$|\.github/.*$'
          sync_dir: 'backend/'
