name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Zip folder
        working-directory: backend
        run: zip -r gc-function-source.zip ./

      - name: Create zip artifact
        uses: actions/upload-artifact@v3
        with:
          name: gc-function-source.zip
          path: backend/gc-function-source.zip

      - name: GC Auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.google_service_account_credentials }}'

      - name: Upload zip to GC
        uses: google-github-actions/upload-cloud-storage@v0
        with:
          path: 'backend/gc-function-source.zip'
          destination: 'bedpresbot'
